const OBRAS = [
	{
		titulo: 'Cuatro corazones con freno y marcha atr&aacute;s',
		autor: 'Jardiel Poncela',
		img: 'img/corazones_web.jpg',
		cuerpo: `Una historia de eterna juventud, llena de personajes disparatados y momentos hilarantes. Nuestros protagonistas descubrir&aacute;n que vivir para siempre, no es sin&oacute;nimo de felicidad y tranquilidad. Las sorpresas se van sucediendo durante tres actos en los que los a&ntilde;os pasan con velocidad y la trama se complica cada vez m&aacute;s. Esperamos provocarles unas risas que les hagan rejuvenecer.`,
		fechas: ['17/05/2025 21:30h'],
		url: 'cuatro-corazones-con-freno-y-marcha-atras-emute',
		tags: ['Comedia'],
		reparto: [
			'Isabel Molina',
			'Isabel Muñoz',
			'Belén García',
			'Diego Salvador',
			'Sergey Gostyuzhev',
			'María Luisa Romero',
			'Margarita Martínez',
			'José Antonio Luque',
			'José Antonio Sánchez',
			'Andrés Gómez-Carreño',
			'Juan Antonio López',
			'David Bautista',
			'Remedios García',
			'Ángel Bautista',
			'Sara Benaisa',
			'Sandra Morán',
			'Leo Benaisa',
		],
		director: 'Fco. de Paula Ramírez',
	},
	{
		titulo: 'La herencia',
		autor: 'Jean-Pierre Martínez',
		img: 'img/herencia_web.jpg',
		cuerpo: `La t&iacute;a Adela acaba de fallecer, y el legado de su maravilloso piso en el centro de Madrid, se convertir&aacute; en un problema para los futuros herederos. La comunidad del edificio, un tanto peculiar, se empe&ntilde;ar&aacute; en celebrar una fiesta de bienvenida, y es que estos vecinos, no aceptar&aacute;n un "no" por respuesta.`,
		url: 'la-herencia-emute',
		fechas: ['18/05/2025 21:30h'],
		tags: ['Comedia'],
		reparto: [
			'Olatz Miguel Ayestaran',
			'Cristian García',
			'Manuela Aguilar',
			'Natalia Estrada',
			'Carmen Gloria Arenas',
			'Marta García',
			'Raquel Pérez',
			'Paula Verónica',
			'Lola García',
			'Meli Paradas',
			'Miguel de Luna',
			'José Gallardo',
			'Blanca Navallas',
		],
		director: 'Jordi Aguilera',
	},
	{
		titulo: 'No cabe un alma',
		autor: 'Leandro Marcos',
		img: 'img/alma_web.jpg',
		cuerpo: `En esta supina burocracia celestial nos encontramos en un cielo abarrotado. &iquest;Qu&eacute; pasar&iacute;a si no hubiera espacio para ning&uacute;n alma m&aacute;s? &iquest;C&oacute;mo reaccionar&iacute;an las almas reci&eacute;n llegadas al cielo al ver qu&eacute; no pueden pasar la puerta celestial? En esta divertida comedia viajaremos al cielo para vivir mil y un enredos celestiales...`,
		url: 'no-cabe-un-alma-emute',
		fechas: ['01/06/2025 21:30h'],
		tags: ['Comedia'],
		reparto: ['Intercambio Escuela Duque de Rivas de Lucena'],
		director: 'Joaquín Serrano',
	},
	{
		titulo: 'La asamblea de las mujeres',
		autor: 'Arist&oacute;fanes',
		img: 'img/asamblea_web.jpg',
		cuerpo: `En esta comedia de Arist&oacute;fanes, las mujeres de Atenas se hacen con el poder de la ciudad, para demostrar a los hombres que son mejores gobernantes que ellos. Mujeres que se revelan contra ese servicial segundo plano al que estaban destinadas. 25 siglos nos separan a nosotras de ellas, sin embargo, &iquest;somos una sociedad diferente?`,
		url: 'la-asamblea-de-las-mujeres',
		fechas: ['07/06/2025 21:30h'],
		tags: ['Comedia clásica'],
		reparto: [
			'Franchesca Cárdenas',
			'Carmen Muñoz',
			'Teresa Ruiz',
			'Pepa Molina',
			'Rosi Sancho',
			'María Escobar',
			'Pilar Parejo',
			'Carmen García',
			'César Menasalvas',
			'José Gálvez',
			'Antonio Parrado',
			'Antonio Navarro "Navi"',
			'Justa Molina',
			'Lola Pozo',
		],
		director: 'Elena Moreno',
	},
	{
		titulo: 'La enferma imaginaria',
		autor: 'Moli&egrave;re',
		img: 'img/enferma_web.jpg',
		cuerpo: `En esta adaptaci&oacute;n del cl&aacute;sico de Moli&egrave;re, la enfermedad de Margot a pesar de las infinitas atenciones de su boticaria y su doctora, no remite. &iquest;Ser&aacute; capaz de sacrificar a su hija Ang&eacute;lica con tal de tener un m&eacute;dico en la familia?`,
		url: 'la-enferma-imaginaria',
		fechas: ['08/06/2025 21:30h'],
		tags: ['Comedia clásica'],
		reparto: [
			'Dori Mira',
			'Mati Mira',
			'Esperanza Ruz',
			'Coqui López',
			'Mª Teresa Ruíz',
			'Isidora Jiménez',
			'José Antonio Díaz',
			'Ana Belén Díaz',
			'Marta de la Rosa',
			'Alberto Rueda',
			'Mayka Ramírez',
			'Carmen Barroso',
		],
		director: 'Elena Moreno',
	},
	{
		titulo: 'Angelina o el honor de un brigadier',
		autor: 'Jardiel Poncela',
		img: 'img/angelina_web.jpg',
		cuerpo: `La j&oacute;ven e inocente Angelina se ha prometido con Rodolfito, todo parece ir como la seda en esta familia de la alta sociedad de 1880, sin embargo, la paz, el sosiego y el amor, dar&aacute;n paso al caos y la deshonra del Brigadier, padre de Angelina. Jardiel Poncela nos presenta esta divertida comedia en verso que representa a modo de caricatura, la Espa&ntilde;a de 1880.`,
		fechas: ['15/06/2025 21:30h'],
		tags: ['Comedia'],
		reparto: [
			'Jesús Tenllado',
			'Siranush',
			'Simón Cubero',
			'Lidia Velasco',
			'Sebastián Ramos',
			'Pepe Corpas',
			'Antonio Navarro "Navi"',
			'Esteban Carneros',
			'Patricia Serralvo',
			'Lucía Montes',
			'Laura Morente',
			'Julita Aranda',
		],
		director: 'Jordi Aguilera',
		url: 'angelina-o-el-honor-de-un-brigadier',
	},
	{
		titulo: 'Criaturitas de Dios (Metafisi-clowns)',
		autor: 'Tom&aacute;s Af&aacute;n',
		img: 'img/clown_web.jpg',
		cuerpo: `&iquest;Qui&eacute;nes somos, de d&oacute;nde venimos, ad&oacute;nde vamos? &iquest;Estamos solos en la galaxia o acompa&ntilde;ados? Estos divertidos payasos, que s&oacute;lo quieren jugar, nos traen la respuesta a todas nuestras dudas existenciales, o no. Amor, poder, religi&oacute;n, amistad, la vida y la muerte, todo tratado con el humor blanco de estas criaturitas teatrales.`,
		url: 'criaturitas-de-dios',
		fechas: ['21/06/2025 21:30h'],
		tags: ['Comedia'],
		reparto: [
			'Juan Antonio López',
			'Juan Francisco Abad Rodríguez',
			'Paula Ramírez',
			'Raquel Casco',
			'Isabel Pérez',
			'María Córdoba',
			'Marina Pérez',
			'Mercedes Montilla',
			'Lidia Casado',
			'Cecilia Sánchez',
			'Ana Muñoz',
			'María Jesús Ruiz',
			'Pilar Ruíz',
		],
		director: 'Fco. de Paula Ramírez',
	},
	{
		titulo: 'Fuimos canciones',
		autor: 'Elena Moreno',
		img: 'img/fuimos_canciones_web.jpg',
		cuerpo: `Macarena ha sido una pringada toda su vida, pero ahora est&aacute; mutando, se est&aacute; convirtiendo en una t&iacute;a guay. Despu&eacute;s de una ruptura sentimental ha estado recomponi&eacute;ndose, pero el mundo vuelve a tambalearse cuando Leo aparece de nuevo en la ciudad. En cada historia, el hilo argumental son las canciones, la BSO de nuestra vida. "Fuimos canciones" es esa historia de crecimiento personal.`,

		fechas: ['22/06/2025 21:30h'],
		tags: ['Teatro musical'],
		reparto: [
			'Maricarmen Sánchez',
			'Laura Martín',
			'Silvia Morales',
			'Laura Morente',
			'Conchi García',
			'Pilar Pacheco',
			'Gloria Sánchez',
			'Mª Jesús Rodríguez',
			'Juande Moreno',
			'Mª Jesús Morente',
			'Manuel Morales',
			'Ana Solórzano',
			'Andrea Pompa',
		],
		director: 'Elena Moreno',
	},
];
